service: dd-sls-plugin-integration-test
frameworkVersion: "3"

plugins:
  - ../dist/src
  - serverless-step-functions

provider:
  name: aws
  region: sa-east-1
  logs:
    restApi:
      accessLogging: true
      executionLogging: false
    httpApi: false
    websocket: true

custom:
  datadog:
    forwarderArn: arn:aws:lambda:us-east-1:000000000000:function:datadog-forwarder
    testingMode: true
    integrationTesting: true
    logLevel: "info"
    subscribeToExecutionLogs: true
    subscribeToStepFunctionLogs: true
    addExtension: false
    exclude:
      - ExcludeThis
      - Exclude-This

functions:
  PythonHello37:
    handler: py_handler.hello
    runtime: python3.7
  PythonHello38:
    handler: py_handler.hello
    runtime: python3.8
  PythonHello39:
    handler: py_handler.hello
    runtime: python3.9
    events:
      - http:
          path: users/create
          method: get
      - httpApi:
          path: /users/update
          method: put
      - websocket: $connect
  JavascriptHello12-x:
    handler: js_handler.hello
    runtime: nodejs12.x
    events:
      - http:
          path: users/create
          method: post
      - httpApi:
          path: /users/remove
          method: delete
      - websocket: $connect
  JavascriptHello14-x:
    handler: js_handler.hello
    runtime: nodejs14.x
  JavascriptHello16-x:
    handler: js_handler.hello
    runtime: nodejs16.x
  JavascriptHello18-x:
    handler: js_handler.hello
    runtime: nodejs18.x
  JavascriptHello20-x:
    handler: js_handler.hello
    runtime: nodejs20.x
  ExcludeThis:
    handler: js_handler.hello
    runtime: nodejs14.x
  Exclude-This:
    handler: js_handler.hello
    runtime: nodejs14.x
  DotnetHello6:
    handler: dotnet_handler.hello
    runtime: dotnet6
  JavaHello8:
    handler: java_handler.hello
    runtime: java8
  JavaHello11:
    handler: java_handler.hello
    runtime: java11
  providedHello:
    handler: provided_handler.hello
    runtime: provided
  RubyHello32:
    handler: rb_handler.hello
    runtime: ruby3.2

resources:
  Resources:
    stepFunction2LogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/vendedlogs/states/stepFunctionLoggingConfigDynamicArn-Logs-dev
    stepFunction3LogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/vendedlogs/states/stepFunctionNoLoggingConfigStaticArn-Logs-dev

stepFunctions:
  stateMachines:
    stepfunction1:
      name: stepFunctionNoLoggingConfig
      definition:
        StartAt: State1
        States:
          State1:
            Type: Task
            Parameters:
              FunctionName:
                Fn::GetAtt: [JavascriptHello18-x, Arn]
            Resource: arn:aws:states:::lambda:invoke
            End: true
    stepfunction2:
      name: stepFunctionLoggingConfigDynamicArn
      loggingConfig:
        level: ALL
        includeExecutionData: true
        destinations:
          - Fn::GetAtt: [stepFunction2LogGroup, Arn]
      definition:
        StartAt: State1
        States:
          State1:
            Type: Task
            Parameters:
              FunctionName:
                Fn::GetAtt: [JavascriptHello18-x, Arn]
            Resource: arn:aws:states:::lambda:invoke
            End: true
    stepfunction3:
      name: stepFunctionNoLoggingConfigStaticArn
      loggingConfig:
        level: ALL
        includeExecutionData: true
        destinations:
          - arn:aws:logs:sa-east-1:425362996713:log-group:/aws/vendedlogs/states/stepFunctionNoLoggingConfigStaticArn-Logs-dev:*
      definition:
        StartAt: State1
        States:
          State1:
            Type: Task
            Parameters:
              FunctionName:
                Fn::GetAtt: [JavascriptHello18-x, Arn]
            Resource: arn:aws:states:::lambda:invoke
            End: true
