// Code generated by serverless-ci e2e-shared sync. DO NOT EDIT.
// Source of truth lives in serverless-ci/e2e/shared -- edit there; local changes are overwritten.

/*
 * Unless explicitly stated otherwise all files in this repository are licensed
 * under the Apache License Version 2.0.
 *
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2026 Datadog, Inc.
 */

import assert from 'node:assert/strict';

import {execPromise} from './exec';
import {FRESHNESS_TAG_KEY} from './naming';

// Runner-agnostic Lambda config verifier: drives the AWS CLI and asserts the deployed
// function's identity with node:assert. "Config present" for Lambda (per spec) = DD
// layers + extension layer + DD_* env vars + tags. The parts that vary per tool (the
// CDK construct vs CFN macro vs sls plugin) are supplied through LambdaVerifierConfig,
// so this file is identical across the Lambda TS repos.

interface LambdaLayer {
  Arn: string;
}
interface LambdaConfiguration {
  FunctionArn: string;
  Handler: string;
  Runtime: string;
  Layers?: LambdaLayer[];
  Environment?: {Variables?: Record<string, string>};
}

export interface FunctionSnapshot {
  handler: string;
  layerArns: string[];
  ddEnv: Record<string, string>;
}

export interface ExpectedLayers {
  node: string;
  extension: string;
}

export interface LambdaVerifierConfig {
  // functionName maps the run-unique service name to the deployed function name, which
  // differs per tool (e.g. sls deploy => `<service>-e2e-hello`).
  functionName: (serviceName: string) => string;
  // expectedLayerArns resolves the pinned node + extension layer ARNs for a region,
  // read from whatever source the tool pins them in (e.g. the plugin's src/layers.json).
  expectedLayerArns: (region: string) => ExpectedLayers;
  // redirectHandler is the wrapper handler the tool redirects to.
  redirectHandler: string;
  // originalHandler, when set, is the expected DD_LAMBDA_HANDLER value (the preserved
  // user handler). Omit to skip the double-wrap check.
  originalHandler?: string;
  // toolTag is the marker tag the tool applies; pattern asserts its shape (e.g. version).
  toolTag: {key: string; pattern: RegExp};
  // env identity. apiKeyVars: at least one must be set. present: must be set (any value).
  // values: must equal exactly (service/env/version identity).
  env: {
    apiKeyVars: string[];
    present: string[];
    values: (serviceName: string) => Record<string, string>;
  };
}

const getConfiguration = async (fnName: string, region: string): Promise<LambdaConfiguration> => {
  const result = await execPromise(
    `aws lambda get-function-configuration --function-name "${fnName}" --region "${region}" --output json`,
  );
  assert.equal(result.exitCode, 0, `get-function-configuration failed: ${result.stderr}`);

  return JSON.parse(result.stdout) as LambdaConfiguration;
};

const getTags = async (functionArn: string, region: string): Promise<Record<string, string>> => {
  const result = await execPromise(
    `aws lambda list-tags --resource "${functionArn}" --region "${region}" --output json`,
  );
  assert.equal(result.exitCode, 0, `list-tags failed: ${result.stderr}`);

  return (JSON.parse(result.stdout).Tags ?? {}) as Record<string, string>;
};

// A normalized view used to assert idempotency (re-apply produces no diff).
export const functionSnapshot = async (
  config: LambdaVerifierConfig,
  serviceName: string,
  region: string,
): Promise<FunctionSnapshot> => {
  const lambda = await getConfiguration(config.functionName(serviceName), region);
  const vars = lambda.Environment?.Variables ?? {};
  const ddEnv: Record<string, string> = {};
  for (const key of Object.keys(vars).sort()) {
    if (key.startsWith('DD_')) {
      ddEnv[key] = vars[key];
    }
  }

  return {
    handler: lambda.Handler,
    layerArns: (lambda.Layers ?? []).map((l) => l.Arn).sort(),
    ddEnv,
  };
};

export const verifyInstrumented = async (
  config: LambdaVerifierConfig,
  serviceName: string,
  region: string,
): Promise<void> => {
  const fnName = config.functionName(serviceName);
  // eslint-disable-next-line no-console
  console.log(`Verifying instrumented state of "${fnName}"...`);
  const lambda = await getConfiguration(fnName, region);
  const vars = lambda.Environment?.Variables ?? {};
  const layerArns = (lambda.Layers ?? []).map((l) => l.Arn);
  const expected = config.expectedLayerArns(region);

  // Handler is redirected to the Datadog wrapper; original preserved (no double-wrap).
  assert.equal(lambda.Handler, config.redirectHandler, 'handler not redirected to the Datadog wrapper');
  if (config.originalHandler !== undefined) {
    assert.equal(
      vars.DD_LAMBDA_HANDLER,
      config.originalHandler,
      'DD_LAMBDA_HANDLER should hold the original handler (a different value means a double-wrap)',
    );
  }

  // Layers: library layer + extension layer, each present exactly once, pinned.
  assert.ok(layerArns.includes(expected.node), `missing pinned Node layer ${expected.node}; got ${JSON.stringify(layerArns)}`);
  assert.ok(
    layerArns.includes(expected.extension),
    `missing pinned extension layer ${expected.extension}; got ${JSON.stringify(layerArns)}`,
  );
  assert.equal(layerArns.filter((a) => a === expected.node).length, 1, 'Node layer attached more than once');
  assert.equal(layerArns.filter((a) => a === expected.extension).length, 1, 'extension layer attached more than once');

  // Env: API key wiring + required DD_* vars + identity.
  assert.ok(config.env.apiKeyVars.some((k) => vars[k]), `no API key wiring env var set (one of ${config.env.apiKeyVars.join(', ')})`);
  for (const key of config.env.present) {
    assert.ok(vars[key], `missing required env var ${key}`);
  }
  for (const [key, want] of Object.entries(config.env.values(serviceName))) {
    assert.equal(vars[key], want, `env var ${key} = ${vars[key]}, want ${want}`);
  }

  // Tags: tool marker (proof the tool tagged the function) + freshness tag (set
  // atomically at creation for the sweeper). Service/env/version identity is carried by
  // the DD_* env vars above and on ingested telemetry.
  const tags = await getTags(lambda.FunctionArn, region);
  assert.match(tags[config.toolTag.key] ?? '', config.toolTag.pattern, `${config.toolTag.key} tag has unexpected shape`);
  assert.ok(tags[FRESHNESS_TAG_KEY], `missing freshness tag ${FRESHNESS_TAG_KEY}`);

  // eslint-disable-next-line no-console
  console.log('All instrumented checks passed.');
};

// After remove the whole stack is torn down -- the function itself is gone, which is the
// clean end-state for this mechanism (no per-resource un-instrument). Assert absence.
export const verifyUninstrumented = async (
  config: LambdaVerifierConfig,
  serviceName: string,
  region: string,
): Promise<void> => {
  const fnName = config.functionName(serviceName);
  // eslint-disable-next-line no-console
  console.log(`Verifying clean (removed) state of "${fnName}"...`);
  const result = await execPromise(
    `aws lambda get-function-configuration --function-name "${fnName}" --region "${region}" --output json`,
  );
  assert.notEqual(result.exitCode, 0, 'function still exists after remove');
  assert.match(
    `${result.stdout} ${result.stderr}`,
    /ResourceNotFoundException|Function not found/,
    `expected ResourceNotFoundException, got: ${result.stderr || result.stdout}`,
  );

  // eslint-disable-next-line no-console
  console.log('Clean-state check passed (function and its DD config are gone).');
};
