// Code generated by serverless-ci e2e-shared sync. DO NOT EDIT.
// Source of truth lives in serverless-ci/e2e/shared -- edit there; local changes are overwritten.

/*
 * Unless explicitly stated otherwise all files in this repository are licensed
 * under the Apache License Version 2.0.
 *
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2026 Datadog, Inc.
 */

import crypto from 'node:crypto';

// Resource-hygiene convention shared across the e2e suites (see spec "Resource
// Hygiene"). The name prefix is the identity + blast-radius guard the sweeper keys on;
// the freshness tag lets it age resources out safely. The tool + platform vary per
// repo, so they are supplied through a config object rather than hardcoded.

export interface E2ENaming {
  tool: string;
  platform: string;
}

// `one` = team marker (`dd-` implied). Prefix is set atomically at creation.
export const namePrefix = (config: E2ENaming, runId: string): string =>
  `one-e2e-${config.tool}-${config.platform}-${runId}`;

export const newRunId = (): string => crypto.randomBytes(4).toString('hex');

// Freshness tag value. Native creation time isn't usable cross-cloud, so we stamp it
// ourselves at create time.
export const FRESHNESS_TAG_KEY = 'one_e2e_created';
// Run-id marker. Standardized across every repo so telemetry and resources cross-reference.
export const RUN_ID_TAG_KEY = 'one_e2e_run_id';
export const freshnessTimestamp = (): string => `${Math.floor(Date.now() / 1000)}`;
